import { createSlice } from "@reduxjs/toolkit";

const initialState = {users: [
  {
    id: 1,
    name: "Aruna P",
    email: "example1@gmail.com",
    password:"1234",
    age: 25,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/originals/af/34/9c/af349c53129b7695488e09d6699f1d81.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "160cm",
    weight: "56kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 2,
    name: "Anusree S",
    email: "example2@gmail.com",
    password:"12345",
    age: 26,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://img.freepik.com/premium-photo/south-indian-girl-with-long-black-hair-is-standing-crowd_905085-76.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "157cm",
    weight: "56kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 3,
    name: "Aswathi M",
    email: "example3@gmail.com",
    password:"12346",
    age: 28,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbp134YP6CiWUHHizOYMGS-7wLFeK0Gp0Sww&s",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "165cm",
    weight: "60kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 4,
    name: "Soumya Krishna",
    email: "example4@gmail.com",
    password:"12347",
    age: 22,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://cdn4.sharechat.com/img_566673_2591c5b5_1676133563489_sc.jpg?tenant=sc&referrer=tag-service&f=489_sc.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "162cm",
    weight: "56kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 5,
    name: "Surya A",
    email: "example5@gmail.com",
    password:"12348",
    age: 24,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQte5fcMOTmjtpS_mbhx8pSttA5Oy0OmCwfgA&s",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "160cm",
    weight: "55kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 6,
    name: "Maya P",
    email: "example6@gmail.com",
    password:"12349",
    age: 25,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/564x/b2/03/08/b203088a1f00febba0cac8f86ee97d32.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "155cm",
    weight: "56kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 7,
    name: "Divya TP",
    email: "example7@gmail.com",
    password:"12340",
    age: 24,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1623091410901-00e2d268901f",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "162cm",
    weight: "56kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 8,
    name: "Gopika Raj",
    email: "example8@gmail.com",
    password:"12341",
    age: 26,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz-M9cVSnA9KOqzy_tuRb3UBjrsv6HlmMgzw&s",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "160cm",
    weight: "58kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 9,
    name: "Keerthana M",
    email: "example9@gmail.com",
    password:"12342",
    age: 23,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://cdn.pixabay.com/photo/2019/08/08/17/25/indian-girl-4393459_960_720.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "158cm",
    weight: "51kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 10,
    name: "Adhithya P",
    email: "example10@gmail.com",
    password:"12343",
    age: 28,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://img.freepik.com/premium-photo/crash-girl-imaged-hd-background-girl-model-smart-hones-normal-cut-girl-queen-girl-imag_88650-3212.jpg?w=360",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "160cm",
    weight: "56kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 11,
    name: "Sreya Das",
    email: "example11@gmail.com",
    password:"12344",
    age: 25,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/736x/f6/db/35/f6db357cfc42ecb8c46eb58698c6bd9b.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "165cm",
    weight: "58kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 12,
    name: "Sneha VM",
    email: "example12@gmail.com",
    password:"1231",
    age: 24,
    gender: "Female",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://e1.pxfuel.com/desktop-wallpaper/166/980/desktop-wallpaper-south-indian-girls-indian-beautiful-girl-mobile-thumbnail.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1999",
    bloodGroup: "O+ve",
    height: "155cm",
    weight: "51kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 13,
    name: "Arun V",
    email: "example13@gmail.com",
    password:"1232",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/564x/00/f3/ba/00f3baed741806ab1cc74e094b30824b.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 14,
    name: "Amay K",
    email: "example14@gmail.com",
    password:"1233",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://pixahive.com/wp-content/uploads/2021/02/An-Indian-boy-375075-pixahive.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 15,
    name: "Prijin M",
    email: "example15@gmail.com",
    password:"1235",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://w0.peakpx.com/wallpaper/459/1009/HD-wallpaper-indian-model-boy-cute-u-wall.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 16,
    name: "Priyank V",
    email: "example16@gmail.com",
    password:"1236",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/736x/52/ae/d1/52aed13c8f4a45af34999a4ced01e795.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 17,
    name: "Nikhil K",
    email: "example18@gmail.com",
    password:"1237",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/originals/f1/11/c2/f111c28c56e09a1d932eaf14cedba68e.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 18,
    name: "Nivin Das",
    email: "example18@gmail.com",
    password:"1238",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://thumbs.dreamstime.com/b/male-model-smiling-camera-resting-rock-mumbai-male-model-smiling-camera-resting-rock-mumbai-maharashtra-123621021.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 19,
    name: "Sangeeth Sathya",
    email: "example19@gmail.com",
    password:"1239",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/originals/8e/7f/de/8e7fde48bf40d2a077730ff3d0970bf3.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 20,
    name: "Rahul PV",
    email: "example20@gmail.com",
    password:"1200",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://pbs.twimg.com/profile_images/1416614643527655427/Kg13Xi3V_400x400.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 21,
    name: "Rohith N",
    email: "example21@gmail.com",
    password:"1211",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/originals/71/ab/da/71abdadd57717f7b0371055f4675bda9.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 22,
    name: "Mithun",
    email: "example22@gmail.com",
    password:"1222",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://i.pinimg.com/736x/69/03/e3/6903e3b3301cb1f5d18cd08f04778171.jpg",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 23,
    name: "Dhinkrit AP",
    email: "example23@gmail.com",
    password:"1221",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcAbiSSwU8SACSsXVJIYZB67xW5uNzEQigFg&s",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
  },
  {
    id: 24,
    name: "Athul KK",
    email: "example24@gmail.com",
    password:"1100",
    age: 30,
    gender: "Male",
    religion: "Hindu",
    caste:"Nair",
    star:"Aswathi",
    chovvadhosham:"No",
    sudhajathakam:"No",
    papajathakam:"No",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOg36GrhMnQ_-7e-_cZB8V2zVhbI7FuORcZg&s",
    phone: "1234567890",
    callTime:"7pm - 9pm",
    birthDate: "25-02-1994",
    bloodGroup: "O+ve",
    height: "170cm",
    weight: "70kg",
    address: {
      address: "ABC House",
      street: "XYZ Street",
      place:"Muzhappilangad",
      district: "Kannur",
      pin: "673300",
    },
    state: "Kerala",
    qualification: "PG",
    education:{
      pg:"MCA",
      ug:"BSc Mathematics",
      plustwo:"PlusTwo",
      sslc:"SSLc",
    },
    schools:{
      plustwo:"ABC School",
      sslc:"XYZ School",
    },
    college:{
      pg:"PQR College",
      ug:"LMN College",
    },
    job: "IT Professional",
    employedin:"Private",
    annualincome:"4 lakhs - 5 lakhs Indian Rupee",
    bodyType:"Slim",
    physicalStatus:"Normal",
    motherTongue:"Malayalam",
    residentialStatus:"Citizen",
    maritalStatus:"Unmarried",
    diet:"Non Vegetarian",
    smoke:"Don't Smoke",
    family:{
      type:"Nuclear Family",
      value:"Traditional",
      status:"Middle Class",
      father:"Prakash P",
      fatherOccupation:"Business",
      mother:"Latha C",
      motherOccupation:"Teacher",
      brother:"(1)Rahul p",
      sister:"Nil",
    },
    interests:{
      reading:"Newspaper",
      movies:"Bollywood",
      sports:"Swimming",
      food:"Biriyani",
      dress:"Casuals",
    },
    
  }
],currentUser:{}}

const UsersSlice = createSlice({
  name: "users",
  initialState: initialState,
  reducers: {
    login:(state,action)=>{
      state.currentUser=action.payload
    },
    register:(state,action)=>{
      state.users.push({id:state.users.length + 1,...action.payload})
    },
    logout:(state,action)=>{
      state.currentUser={}
    }
  },
});
export const {login,register,logout}=UsersSlice.actions
export default UsersSlice.reducer;
